### ISSUE TITLE
install does not work

### ISSUE THREAD

**Issue by dani-a-dolan** [11joselu/cypress-to-playwright#1]

**Comment by 11joselu** [comment]
Can you expand a little?

Reproducible steps etc...

**Comment by dani-a-dolan** [comment]
running the npm install command does not work

npm install @11joselu/cypress-to-playwright -D

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@11joselu%2fcypress-to-playwright - Not found
npm ERR! 404 
npm ERR! 404  '@11joselu/cypress-to-playwright@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:

**Comment by nick-matthai** [comment]
Commenting to follow - having the same issue

**Comment by 11joselu** [comment]
Fixed now.
