### ISSUE TITLE
Error when trying to convert

### ISSUE THREAD

**Issue by NickMMG** [11joselu/cypress-to-playwright#3]
1. Installed package npm install @11joselu/cypress-to-playwright -D
2. I run the command npx @11joselu/cypress-to-playwright cypress/e2e and get an error

 const body = identifier(bodyProp.initializer.getText());
                                         ^

TypeError: Cannot read properties of undefined (reading 'initializer')
    at Object.createRouteIntercept [as playwrightIntercept] ....../node_modules/@11joselu/cypress-to-playwright/lib/core/converters/node-factory.js:217:42)
    at commands (...../node_modules/@11joselu/cypress-to-playwright/lib/core/converters/transform.js:133:24)
    at visit (......./node_modules/@11joselu/cypress-to-playwright/lib/core/converters/transform.js:57:28) 
    at visitArrayWorker (.........\node_modules\@11joselu\cypress-to-playwright\node_modules\typescript\lib\typescript.js:91402:48)
    at visitNodes (......\node_modules\@11joselu\cypress-to-playwright\node_modules\typescript\lib\typescript.js:91366:23)
    at visitEachChildOfBlock (........\node_modules\@11joselu\cypress-to-playwright\node_modules\typescript\lib\typescript.js:91792:54)
    at Object.visitEachChild (........\node_modules\@11joselu\cypress-to-playwright\node_modules\typescript\lib\typescript.js:91546:42)
    at visit (........./node_modules/@11joselu/cypress-to-playwright/lib/core/converters/transform.js:16:27) 
    at visitNode (.......\node_modules\@11joselu\cypress-to-playwright\node_modules\typescript\lib\typescript.js:91314:23)
    at visitFunctionBody (.....\node_modules\@11joselu\cypress-to-playwright\node_modules\typescript\lib\typescript.js:91510:23)

**Comment by 11joselu** [comment]
Some `cy.intercept` [is not supported](https://github.com/11joselu/cypress-to-playwright/blob/main/docs/migration.md#commands) 

Can you provide an example of what kind of intercept are you using in your code?

**Comment by NickMMG** [comment]
i have tests with cy.intercept and without

     it('viewing KXML', () => {
	cy.visit('/kxml-preview')
	const html = '<!DOCTYPE html><html><body><p>Hello</p></body></html>'
	cy.intercept('POST', '/api/proxy/text/**', {
		statusCode: 200,
		body: html,
	})
	cy.findByRole('textbox', { name: 'KXML' }).type('<TEXTFIELD><P>Hello</P></TEXTFIELD>')
	cy.findByTestId('kodeks-html-frame').should('have.attr', 'srcDoc', html)
    })


	it('keyboard shortcuts', () => {
		cy.openEditor({ debug: true })
		cy.getEditor().type('Hello World!')
		cy.getEditor().type('{ctrl+j}')
		cy.assertKxml(
			'<TEXTFIELD><P CLASS="formattext topleveltext" ALIGN="justify">Hello World!</P></TEXTFIELD>',
		)
		cy.getEditor().type('{ctrl+e}')
		cy.assertKxml(
			'<TEXTFIELD><P CLASS="formattext topleveltext centertext" ALIGN="center">Hello World!</P></TEXTFIELD>',
		)
		cy.getEditor().type('{ctrl+r}')
		cy.assertKxml(
			'<TEXTFIELD><P CLASS="formattext topleveltext" ALIGN="right">Hello World!</P></TEXTFIELD>',
		)
		cy.getEditor().type('{ctrl+l}')
		cy.assertKxml(
			'<TEXTFIELD><P CLASS="formattext topleveltext">Hello World!</P></TEXTFIELD>',
		)
	})

**Comment by 11joselu** [comment]
I tested your code and the converter does not throw any error:

Note: tests the last version @11joselu/cypress-to-playwright@0.0.14 I just add a debug log if there are any error 

```javascript
it('viewing KXML', () => {
  cy.visit('/kxml-preview');
  const html = '<!DOCTYPE html><html><body><p>Hello</p></body></html>';
  cy.intercept('POST', '/api/proxy/text/**', {
    statusCode: 200,
    body: html,
  });
  cy.findByRole('textbox', { name: 'KXML' }).type('<TEXTFIELD><P>Hello</P></TEXTFIELD>');
  cy.findByTestId('kodeks-html-frame').should('have.attr', 'srcDoc', html);
});

it('keyboard shortcuts', () => {
  cy.openEditor({ debug: true });
  cy.getEditor().type('Hello World!');
  cy.getEditor().type('{ctrl+j}');
  cy.assertKxml('<TEXTFIELD><P CLASS="formattext topleveltext" ALIGN="justify">Hello World!</P></TEXTFIELD>');
  cy.getEditor().type('{ctrl+e}');
  cy.assertKxml('<TEXTFIELD><P CLASS="formattext topleveltext centertext" ALIGN="center">Hello World!</P></TEXTFIELD>');
  cy.getEditor().type('{ctrl+r}');
  cy.assertKxml('<TEXTFIELD><P CLASS="formattext topleveltext" ALIGN="right">Hello World!</P></TEXTFIELD>');
  cy.getEditor().type('{ctrl+l}');
  cy.assertKxml('<TEXTFIELD><P CLASS="formattext topleveltext">Hello World!</P></TEXTFIELD>');
});

```

And the output was:
```javascript
import { test, expect } from '@playwright/test';
test('viewing KXML', async ({ page }) => {
  await page.goto('/kxml-preview');
  const html = '<!DOCTYPE html><html><body><p>Hello</p></body></html>';
  page.route('/api/proxy/text/.*', (route) => {
    if (route.request().method() !== 'POST') {
      route.fallback();
      return;
    }
    route.fulfill({ status: 200, body: html });
  });
  cy.findByRole('textbox', { name: 'KXML' }).type('<TEXTFIELD><P>Hello</P></TEXTFIELD>');
  cy.findByTestId('kodeks-html-frame').should('have.attr', 'srcDoc', html);
});
test('keyboard shortcuts', async ({ page }) => {
  cy.openEditor({ debug: true });
  cy.getEditor().type('Hello World!');
  cy.getEditor().type('{ctrl+j}');
  cy.assertKxml('<TEXTFIELD><P CLASS="formattext topleveltext" ALIGN="justify">Hello World!</P></TEXTFIELD>');
  cy.getEditor().type('{ctrl+e}');
  cy.assertKxml('<TEXTFIELD><P CLASS="formattext topleveltext centertext" ALIGN="center">Hello World!</P></TEXTFIELD>');
  cy.getEditor().type('{ctrl+r}');
  cy.assertKxml('<TEXTFIELD><P CLASS="formattext topleveltext" ALIGN="right">Hello World!</P></TEXTFIELD>');
  cy.getEditor().type('{ctrl+l}');
  cy.assertKxml('<TEXTFIELD><P CLASS="formattext topleveltext">Hello World!</P></TEXTFIELD>');
});

```

**Comment by arun1991ram** [comment]
@11joselu , Could you please tell me how to convert cypress code from **.ts** to playwright .ts scripts ?
